### ISSUE TITLE
튜토리얼 팝업창

### ISSUE THREAD

**Issue by junnie082** [junnie082/block-it#10]
- [x] 옵션 화면의 'Tutorial' 버튼을 누르면 튜토리얼이 뜨게 된다.
- [x] 게임 규칙과 조작법을 동시에 확인할 수 있다.
- [x] 형식은 아래 그림과 같이 뒤로 가기(화살표), 넘어 가기(화살표), 그만 보기(X)
- [ ] [대본(한국어, 높임말)](https://github.com/junnie082/Quoridor/issues/2)

![Image](https://user-images.githubusercontent.com/88719152/234158946-44906e09-b618-46a0-a128-68ae2778c3c3.png)
![Image](https://user-images.githubusercontent.com/88719152/234158937-493dc404-13a4-4d9a-b013-3fdb0d6d3689.png)
![Image](https://user-images.githubusercontent.com/88719152/234158935-a8f7f1f2-6dee-404c-b440-ee4cf4bb3bc9.png)
![Image](https://user-images.githubusercontent.com/88719152/234158944-29bcbb59-40a9-4e56-898c-5a28d3155bd4.png)
![Image](https://user-images.githubusercontent.com/88719152/234158939-2daba471-1c35-4218-9ecc-e07a69379970.png)
![Image](https://user-images.githubusercontent.com/88719152/234158945-8eaa3543-ab2a-4a07-8026-45919e154d98.png)
![Image](https://user-images.githubusercontent.com/88719152/234158940-a7d0d43a-0728-44a4-97f7-eac4da7adf63.png)
![Image](https://user-images.githubusercontent.com/88719152/234158942-2c5ba28f-d067-41c4-b689-bf71fac62b65.png)
![Image](https://user-images.githubusercontent.com/88719152/234158943-310dfed5-8909-47c5-9d48-3d699b06de69.png)
![Image](https://user-images.githubusercontent.com/88719152/234158941-a4b6a7fc-df2a-4723-b56d-c009a5ef964c.png)
![Image](https://user-images.githubusercontent.com/88719152/234158936-86713534-a48e-4070-894a-74aea55c3414.png)
![Image](https://user-images.githubusercontent.com/88719152/234158947-b5ebc5b6-7a05-49b9-9ff3-24fe5dd8aa5d.png)
![Image](https://user-images.githubusercontent.com/88719152/234158948-db143291-1ce9-405c-9bb7-94dc7b36fb39.png)

**Comment by seong0929** [comment]
- [ ] 튜토리얼에 넣을 그림 필요
- 영어 버전은 예시 그대로 해도 되나요?

**Comment by seong0929** [comment]
영어 버전 피그마 그대로 사용 예정

**Comment by junnie082** [comment]
1.
[상단] The one who reahces the \n
opponent’s  starting line \n
wins the game. \n

[그림] tutorial_1

2. 
[상단] 
You have two choices: \n
* move the horse \n
* put one plank on the board \n

[그림] tutorial_2

[하단] This is the spot where you can go. 
Select one of these yellow circles.

3.
[상단] 
You have two choices: \n
* move the horse \n
* put one plank on the board \n

[그림] tutorial_3

[하단] Select the position where you want to
put the plank, and press the [put] 
button so that you can confirm.

4.
[상단]
Each plank takes two squares
of the board. 
Not one, three, ... etc.

[그림] tutorial_4-1

5.
[상단] 
If players encounter, each
player can jump and get to 
the place beyond the 
opponent.

[그림] tutorial_4-2

6.
[상단]
Each plank shouldn’t invade 
the boundaries.

[그림] tutorial_4-3

7.
[상단]
You can’t isolate players with planks. Each player needs at least one way to make the goal. 

[그림] tutorial_4-4

8.
[상단] 
The cases when you encounter the oponent.
Case #1.

[그림] case1

[하단]
player1
player2
places where player1 can go

9.
[상단]
The cases when you encounter the oponent.
Case #2.

[그림] case2

[하단]
player1
player2
places where player1 can go

10.
[상단] 
The cases when you encounter the oponent.
Case #3.

[그림] case3

[하단]
player1
player2
places where player1 can go

11.
[상단] 
The cases when you encounter the oponent.
Case #4.

[그림] case4

[하단]
player1
player2
places where player1 can go

12.
[상단] 
The cases when you encounter the oponent.
Case #5.

[그림] case5

[하단]
player1
player2
places where player1 can go

13.
[상단] 
The cases when you encounter the oponent.
Case #6.

[그림] case6

[하단]
player1
player2
places where player1 can go

14.
Quoridor supports three modes! \n
 You can play with your local friends, \n
you can play with the world's hidden talents, \n 
or you can play with the AI. \n
  Quoridor is a 1997 Mensa Select abstract strategy game that improves spatial awareness and is good for brain development. If you practice and play steadily, your mind skills will also grow!  Play with friend is a mode made to play with offline friends. Compete among your friends to see who can play Quorido the best!
 Play with others is a mode made to play with players from all over the world. Defeat hidden masters, earn points, and update your score and rank to challenge the world's best masters!
 Play with AI is a mode made to play with artificial intelligence. You can choose easy, medium, or hard difficulty, and you can practice before playing with others.
