### ISSUE TITLE
옵션

### ISSUE THREAD

**Issue by junnie082** [junnie082/block-it#13]
[피그마](https://www.figma.com/file/axcqNlMNnMknrpX1aesM97/Quoridor?node-id=0%3A1&t=vLyf2wqSAOD6NTIx-1)

#  사운드

- [x] 배경 음악
- [x] 효과음
- [x] 진동은 토글로 온오프

- [x] 슬라이드 바로 볼륨 조절

# 튜토리얼

- [x] 튜토리얼 버튼을 누르면 팝업창이 뜸

# 언어

- [ ] 한국어
- [ ] 영어

![Image](https://user-images.githubusercontent.com/88719152/234156831-fda3d807-43de-4e34-8a53-24fe1c0b7c28.png)

**Comment by seong0929** [comment]
다른 씬에서 이용되는 옵션 프리팹화
- ![Image](https://github.com/junnie082/block-it/assets/50050003/85652193-f636-4fda-a048-143a30fc6f43)
  - BGM 슬라이더
  - sound effect 슬라이더
  - vibration 토글
  - language 버튼

**Comment by seong0929** [comment]
- [로딩창](https://github.com/users/junnie082/projects/2/views/1?pane=issue&itemId=30851134) to do로 "SoundManager 스크립트가 사라지지 않고 중복이 되지 않도록 초기 로딩 화면 필요" 해결
- [언어 버전](https://github.com/users/junnie082/projects/2/views/1?pane=issue&itemId=30851146) to do로 "한글이 기본이기에 한국어 에셋이 필요" & "언어 부분은 번역 방법은 아래와 같이 다양하며, 방법에 따라 구현이 달라질 수 있어, 구현하지 않음" 해결
- [디자인 에셋](https://github.com/junnie082/block-it/discussions/30)로 UI 디자인 에셋 설정
