### ISSUE TITLE
로딩창

### ISSUE THREAD

**Issue by junnie082** [junnie082/block-it#44]
- [x] SoundManager  적용
- [x] 아래 그림과 같은 레이아웃을 가짐
- [x] Guest Mode 터치 시 Home 씬으로 이동
- [x] Sign Up 터치 시 SignUp 씬으로 이동

![Image](https://user-images.githubusercontent.com/88719152/248164828-9ae0fc08-e1d9-4106-90c7-0d067e44ec04.png)

**Comment by seong0929** [comment]
회원 가입이 되어 있으면, 버튼이 사라지고 클릭 혹은 1초뒤 자동으로 홈씬으로 이동하게 만들었으나, 회원 가입 기능이 완성 되어야 확인 가능

**Comment by seong0929** [comment]
### 로딩씬 제작
- 게스트 클릭 시 홈으로 이동
- 회원 가입 클릭 시 회원 가입 씬 이동
- 회원 가입이 되어 있으면 클릭 혹은 1초 뒤 홈씬으로 이동
### 미구현 이슈
- SignUp씬 필요
- 회원가입이 되어있는 지 확인하는 기능 피룡

**Comment by junnie082** [comment]
- [ ] Sign Up -> Sign In 으로 바꾸고 로그인 화면으로 넘어감

![Image](https://github.com/SeoulTechTCPGame/block-it/assets/88719152/aa4034f1-051b-45dc-acc7-14bc9b3c13fc)
